version: "3.8"

services:
  medicamentos:
    build: .
    container_name: sistema-medicamentos
    restart: always

    volumes:
      - ./database.db:/app/database.db

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kalina.rule=Host(`kalina.8april.com.br`)"
      - "traefik.http.routers.kalina.entrypoints=websecure"
      - "traefik.http.routers.kalina.tls.certresolver=letsencrypt"
      - "traefik.http.services.kalina.loadbalancer.server.port=8000"

    networks:
      - root_default


networks:
  root_default:
    external: true